name: flutter_workspace
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  ghpages: ^3.0.0
  build_runner: ^2.1.5 
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400 
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600

homepage: https://legogoua.github.io/flutter_project/

scripts:
  deploy: flutter pub run ghpages:deploy
